[versions]
skyBuildLogic = "1.2.3"
skyWidgetCompose = "1.0.1"
activityCompose = "1.13.0"
lottieCompose = "6.7.1"

[libraries]
# 必须库
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# 非必须库
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottieCompose" }
skyWidgetCompose = { module = "com.sky.lib:SkyWidgetCompose", version.ref = "skyWidgetCompose" }

[plugins]
# 必须插件
sky-android-application = { id = "sky.android.application", version.ref = "skyBuildLogic" }
sky-android-application-flavors = { id = "sky.android.application.flavors", version.ref = "skyBuildLogic" }
sky-android-library = { id = "sky.android.library", version.ref = "skyBuildLogic" }
sky-android-hilt = { id = "sky.android.hilt", version.ref = "skyBuildLogic" }
sky-android-publish = { id = "sky.android.publish", version.ref = "skyBuildLogic" }

